<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProfessionalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'F',
    			'data_nascimento' => Carbon::parse('2000-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    		  'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'naturalidade_provincia_id' => '1',
          'naturalidade_distrito_id' => '2',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '2',
          'posto_administrativo_id' => '7',
    			'cidade' => 'Maputo',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
          'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('2001-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '1',
          'naturalidade_distrito_id' => '2',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '2',
          'posto_administrativo_id' => '8',
    			'cidade' => 'Maputo',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
          'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'F',
    			'data_nascimento' => Carbon::parse('1991-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '1',
          'naturalidade_distrito_id' => '2',
          'endereco_provincia_id' => '1',
          'distrito_id' => '2',
          'posto_administrativo_id' => '9',
    			'cidade' => 'Maputo',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1992-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '1',
          'naturalidade_distrito_id' => '2',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '2',
          'posto_administrativo_id' => '10',
    			'cidade' => 'Maputo',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1993-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '1',
          'naturalidade_distrito_id' => '2',
          'endereco_provincia_id' => '1',
          'distrito_id' => '2',
          'posto_administrativo_id' => '7',
    			'cidade' => 'Montepuez',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1998-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
    			'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1995-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('2000-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1995-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('2000-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1995-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1994-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1991-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '1',
          'cidade' => 'CHANGANE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 12,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1994-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('2000-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '2',
          'cidade' => 'CHIBUTO',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 10,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '3',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '4',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '4',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );

    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
          'naturalidade_provincia_id' => '2',
          'naturalidade_distrito_id' => '19',
          'endereco_provincia_id' => '2',
          'distrito_id' => '19',
          'posto_administrativo_id' => '4',
          'cidade' => 'CHAIMITE',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
                        'classe_id' => 7,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    }
}
