<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProfessionalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),    			
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    	
    	DB::table ( 'professional' )->insert ( [
    			'nome' => str_random(10),
    			'genero' => 'M',
    			'data_nascimento' => Carbon::parse('1999-01-01'),
    			'tipo_documento_id' => '1',
    			'numero_documento' => str_random(13),
    			'data_emissao_documento' => Carbon::parse('2015-01-01'),
    			'data_validade_documento' => Carbon::parse('2020-01-01'),
    			'nacionalidade_id' => '1',
    			'naturalidade_provincia_id' => '1',
    			'endereco_provincia_id' => '1',
    			'distrito_id' => '1',
    			'cidade_id' => '17',
    			'bairro' => str_random(10),
    			'rua' => str_random(10),
    			'quarteirao' => str_random(10),
    			'celula' => str_random(10),
    			'casa' => str_random(10),
    			'tem_nivel_academico' => 1,
    			'telefone' => '12345678901',
    			'email' => str_random(10),
    	] );
    }
}
